### ISSUE TITLE
No Api Key

### ISSUE THREAD

**Issue by bernamaxim** [indragunawanrtf/ember-mtrlze-map#1]
Masalahnya hanya ada pada API key tidak terbaca.

Sudah coba generate API key yang baru?

Bila masih bermasalah, coba pakai tutorial google maps Ember CLI yang lain.

![screen shot 2018-01-22 at 8 16 04 pm](https://user-images.githubusercontent.com/2969479/35222634-2717766a-ffb1-11e7-816c-ee51fb33c1b2.png)

**Comment by indragunawanrtf** [comment]
ok pak
